### ISSUE TITLE
Change url of webfonts.css to load them from webapp

### ISSUE THREAD

**Issue by atrandafir** [thegooddata/social#40]
Right now we use the same fonts on webapp, blog and collaborate, but the font files are repeated in each application.

That means that a user visiting first webapp and then blog, and then collaborate, will load the fonts 3 times.

To avoid that we should modify Drupal to load the fonts CSS from webapp:
https://www.thegooddata.org/themes/tgd/css/vendor/webfonts.css

I can see right now the fonts come from this file but this file contains more than fonts so you could remove fonts from this file and load separately the other one, or keep this file and edit the paths to each font file to point absolutely to webapp fonts:
https://collaborate.thegooddata.org/sites/default/files/css/css_RwIXQkou74d6MxNn1uP3-1ijVT9HYNK4VO4wmAHwRYo.css

Keep in mind that we're talking only about ProximaNova fonts, not fontawesome, fontawesome should be left as it is.

Issue related to: https://github.com/thegooddata/webapp/issues/115

**Comment by josereyero** [comment]
Lo he configurado en PRE, pero da un error (Access-Control-Allow-Origin) y las fuentes no cargan. Creo que tienes que configurar algún header en el servidor para que estos archivos se puedan usar desde otro dominio...?

Esto es lo que me sale en el debugger de Chrome:

2(index):1 Font from origin 'https://www.thegooddata.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://local.thegooddata.org' is therefore not allowed access.

Relacionado: http://stackoverflow.com/questions/23981866/same-origin-restriction-blocking-font-from-same-origin

**Comment by josereyero** [comment]
Postponing, depending on related issue - which has been posponed too.
I will be rolling back changes on PRE.

**Comment by atrandafir** [comment]
I have closed the related issues that were also Posponed so we don't have them in the issues list for now. If you agree with that @josereyero also close this one so you don't see it anymore.

**Comment by josereyero** [comment]
Ok, fine with that, closing.
(Rollled back changes in collaborate-pre, back to branch 'develop')
